package com.example.tutiya.mybatis.entity.generated;

public class Tally {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Tally.Num
     *
     * @mbg.generated Tue Oct 30 17:36:24 JST 2018
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Tally.Num
     *
     * @return the value of Tally.Num
     *
     * @mbg.generated Tue Oct 30 17:36:24 JST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Tally.Num
     *
     * @param num the value for Tally.Num
     *
     * @mbg.generated Tue Oct 30 17:36:24 JST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}