package com.example.tutiya.mybatis.entity.generated;

public class Captains {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Captains.CaptainId
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    private Integer captainid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Captains.Name
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Captains.CaptainId
     *
     * @return the value of Captains.CaptainId
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    public Integer getCaptainid() {
        return captainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Captains.CaptainId
     *
     * @param captainid the value for Captains.CaptainId
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    public void setCaptainid(Integer captainid) {
        this.captainid = captainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Captains.Name
     *
     * @return the value of Captains.Name
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Captains.Name
     *
     * @param name the value for Captains.Name
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    public void setName(String name) {
        this.name = name;
    }
}