package com.example.tutiya.mybatis.entity.generated;

public class Teams {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Teams.TeamId
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    private Integer teamid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Teams.TeamName
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    private String teamname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Teams.CaptainId
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    private Integer captainid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Teams.Version
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Teams.TeamId
     *
     * @return the value of Teams.TeamId
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    public Integer getTeamid() {
        return teamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Teams.TeamId
     *
     * @param teamid the value for Teams.TeamId
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    public void setTeamid(Integer teamid) {
        this.teamid = teamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Teams.TeamName
     *
     * @return the value of Teams.TeamName
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    public String getTeamname() {
        return teamname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Teams.TeamName
     *
     * @param teamname the value for Teams.TeamName
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    public void setTeamname(String teamname) {
        this.teamname = teamname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Teams.CaptainId
     *
     * @return the value of Teams.CaptainId
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    public Integer getCaptainid() {
        return captainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Teams.CaptainId
     *
     * @param captainid the value for Teams.CaptainId
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    public void setCaptainid(Integer captainid) {
        this.captainid = captainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Teams.Version
     *
     * @return the value of Teams.Version
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Teams.Version
     *
     * @param version the value for Teams.Version
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}