package com.example.tutiya.mybatis.mapper.generated;

import com.example.tutiya.mybatis.entity.generated.Captains;
import com.example.tutiya.mybatis.entity.generated.CaptainsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CaptainsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Captains
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    long countByExample(CaptainsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Captains
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    int deleteByExample(CaptainsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Captains
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    int deleteByPrimaryKey(Integer captainid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Captains
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    int insert(Captains record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Captains
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    int insertSelective(Captains record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Captains
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    List<Captains> selectByExample(CaptainsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Captains
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    Captains selectByPrimaryKey(Integer captainid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Captains
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    int updateByExampleSelective(@Param("record") Captains record, @Param("example") CaptainsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Captains
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    int updateByExample(@Param("record") Captains record, @Param("example") CaptainsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Captains
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    int updateByPrimaryKeySelective(Captains record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Captains
     *
     * @mbg.generated Fri Nov 02 17:53:19 JST 2018
     */
    int updateByPrimaryKey(Captains record);
}